set backupdir=~/.vim/temp
set directory=~/.vim/temp
set undodir=~/.vim/undo
set nocompatible
filetype plugin on
filetype indent plugin on
syntax on
set tabstop=4
colorscheme molokai

map <F6> :setlocal spell spelllang=es_mx<CR>
map <F4> :setlocal spell spelllang=en_us<CR>
inoremap jk <Esc>
inoremap kj <Esc>
vnoremap <C-c> "+y
vnoremap <C-v> "+p 
autocmd Filetype rmd map <F5> :!echo<space>"require(rmarkdown);<space>render('<c-r>%')"<space>\|<space>R<space>--vanilla<enter>

autocmd FileType * call <SID>def_base_syntax() " autocmd Syntax may be better
function! s:def_base_syntax()
  " Simple example
  syntax match commonOperator "\(+\|=\|-\|\^\|\*\)"
  syntax match baseDelimiter ","
  hi link commonOperator Operator
  hi link baseDelimiter Special
endfunction
